# -*- coding: utf-8 -*-
"""Future_DS_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDKs8kyHPzmbCMkno19CbjOrLckfIWHU

# 📊 Customer Retention & Churn Analysis

# Future Interns – Data Science & Analytics Task 2

Objective:
Analyze customer behavior, identify churn patterns and retention drivers,
understand customer lifetime patterns, and provide actionable business
recommendations to reduce customer churn.

Tools Used:
Python, Pandas, NumPy, Matplotlib, Seaborn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

sns.set_style("whitegrid")

print("Libraries imported successfully!")

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
print("Dataset loaded successfully!")

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.head()

df.info()

df.describe()

missing_values = df.isnull().sum()
missing_values[missing_values > 0]

print("Number of duplicate rows:", df.duplicated().sum())

df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

print(df["TotalCharges"].dtype)

df.isnull().sum()[df.isnull().sum() > 0]

df["TotalCharges"] = df["TotalCharges"].fillna(0)
print("Missing TotalCharges:", df["TotalCharges"].isnull().sum())

df = df.drop_duplicates()
print("Dataset shape after removing duplicates:", df.shape)

df.info()

df["Churn_Encoded"] = df["Churn"].map({
    "Yes": 1,
    "No": 0
})

df[["Churn", "Churn_Encoded"]].head()

total_customers = len(df)
churned_customers = df["Churn_Encoded"].sum()
retained_customers = total_customers - churned_customers

churn_rate = (churned_customers / total_customers) * 100
retention_rate = 100 - churn_rate

print("Total Customers:", total_customers)
print("Churned Customers:", churned_customers)
print("Retained Customers:", retained_customers)
print("Churn Rate:{:.2f}%".format(churn_rate))
print("Retention Rate:{:.2f}%".format(retention_rate))

plt.figure(figsize=(7, 5))
sns.countplot(data=df, x="Churn")

plt.title("Customer Churn Distribution")
plt.xlabel("Churn Status")
plt.ylabel("Number of Customers")

plt.show()

churn_distribution = df["Churn"].value_counts(normalize=True) * 100

print(churn_distribution)
plt.figure(figsize=(6, 6))

plt.pie(
    churn_distribution,
    labels=churn_distribution.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Customer Churn vs Retention")

plt.show()

def churn_by_category(column):
    result = (
        df.groupby(column)["Churn_Encoded"]
        .agg(["count", "sum", "mean"])
        .reset_index()
    )

    result.columns = [
        column,
        "Total Customers",
        "Churned Customers",
        "Churn Rate"
    ]

    result["Churn Rate"] = result["Churn Rate"] * 100

    return result.sort_values("Churn Rate", ascending=False)

contract_churn = churn_by_category("Contract")

contract_churn

plt.figure(figsize=(9, 5))

sns.barplot(
    data=contract_churn,
    x="Contract",
    y="Churn Rate"
)

plt.title("Churn Rate by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Churn Rate (%)")

plt.show()

df["Tenure_Group"] = pd.cut(
    df["tenure"],
    bins=[-1, 12, 24, 48, 60, np.inf],
    labels=[
        "0-12 Months",
        "13-24 Months",
        "25-48 Months",
        "49-60 Months",
        "60+ Months"
    ]
)

df["Tenure_Group"].value_counts().sort_index()

tenure_churn = churn_by_category("Tenure_Group")

tenure_churn

plt.figure(figsize=(10, 5))

sns.barplot(
    data=tenure_churn,
    x="Tenure_Group",
    y="Churn Rate"
)

plt.title("Churn Rate by Customer Tenure")
plt.xlabel("Customer Tenure")
plt.ylabel("Churn Rate (%)")

plt.xticks(rotation=20)

plt.show()

internet_churn = churn_by_category("InternetService")

internet_churn

plt.figure(figsize=(8, 5))

sns.barplot(
    data=internet_churn,
    x="InternetService",
    y="Churn Rate"
)

plt.title("Churn Rate by Internet Service")
plt.xlabel("Internet Service")
plt.ylabel("Churn Rate (%)")

plt.show()

payment_churn = churn_by_category("PaymentMethod")

payment_churn

plt.figure(figsize=(11, 5))

sns.barplot(
    data=payment_churn,
    x="PaymentMethod",
    y="Churn Rate"
)

plt.title("Churn Rate by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Churn Rate (%)")

plt.xticks(rotation=25)

plt.show()

support_churn = churn_by_category("TechSupport")

support_churn

plt.figure(figsize=(8, 5))

sns.barplot(
    data=support_churn,
    x="TechSupport",
    y="Churn Rate"
)

plt.title("Churn Rate by Tech Support")
plt.xlabel("Tech Support")
plt.ylabel("Churn Rate (%)")

plt.show()

security_churn = churn_by_category("OnlineSecurity")

security_churn

plt.figure(figsize=(8, 5))

sns.barplot(
    data=security_churn,
    x="OnlineSecurity",
    y="Churn Rate"
)

plt.title("Churn Rate by Online Security")
plt.xlabel("Online Security")
plt.ylabel("Churn Rate (%)")

plt.show()

plt.figure(figsize=(10, 6))

sns.boxplot(
    data=df,
    x="Churn",
    y="MonthlyCharges"
)

plt.title("Monthly Charges by Churn Status")
plt.xlabel("Churn")
plt.ylabel("Monthly Charges")

plt.show()

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x="tenure",
    y="MonthlyCharges",
    hue="Churn",
    alpha=0.6
)

plt.title("Customer Tenure vs Monthly Charges")
plt.xlabel("Tenure (Months)")
plt.ylabel("Monthly Charges")

plt.show()

senior_churn = churn_by_category("SeniorCitizen")

senior_churn

senior_churn["Customer Type"] = senior_churn["SeniorCitizen"].map({
    0: "Non-Senior Citizen",
    1: "Senior Citizen"
})

senior_churn

plt.figure(figsize=(8, 5))

sns.barplot(
    data=senior_churn,
    x="Customer Type",
    y="Churn Rate"
)

plt.title("Churn Rate by Customer Type")
plt.xlabel("Customer Type")
plt.ylabel("Churn Rate (%)")

plt.show()

dependents_churn = churn_by_category("Dependents")

dependents_churn

plt.figure(figsize=(7, 5))

sns.barplot(
    data=dependents_churn,
    x="Dependents",
    y="Churn Rate"
)

plt.title("Churn Rate by Dependents")
plt.xlabel("Has Dependents")
plt.ylabel("Churn Rate (%)")

plt.show()

average_tenure = df["tenure"].mean()

print("Average Customer Tenure: {:.2f} months".format(average_tenure))

plt.figure(figsize=(10, 5))

sns.histplot(
    data=df,
    x="tenure",
    bins=30
)

plt.title("Customer Tenure Distribution")
plt.xlabel("Tenure (Months)")
plt.ylabel("Number of Customers")

plt.show()

tenure_retention = df.groupby("Tenure_Group")["Churn_Encoded"].agg(
    ["count", "mean"]
).reset_index()

tenure_retention.columns = [
    "Tenure Group",
    "Total Customers",
    "Churn Rate"
]

tenure_retention["Churn Rate"] *= 100

tenure_retention["Retention Rate"] = (
    100 - tenure_retention["Churn Rate"]
)

tenure_retention

plt.figure(figsize=(10, 5))

sns.barplot(
    data=tenure_retention,
    x="Tenure Group",
    y="Retention Rate"
)

plt.title("Customer Retention Rate by Tenure")
plt.xlabel("Customer Tenure")
plt.ylabel("Retention Rate (%)")

plt.xticks(rotation=20)

plt.show()

# Churn rate by contract and tenure group

contract_tenure_churn = (
    df.groupby(["Contract", "Tenure_Group"], observed=True)["Churn_Encoded"]
    .mean()
    .reset_index()
)

# Convert churn rate to percentage
contract_tenure_churn["Churn_Encoded"] *= 100

contract_tenure_churn.head(20)

# Visualize churn rate by contract and tenure group

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))

sns.barplot(
    data=contract_tenure_churn,
    x="Tenure_Group",
    y="Churn_Encoded",
    hue="Contract"
)

plt.title("Churn Rate by Contract and Tenure Group")
plt.xlabel("Tenure Group")
plt.ylabel("Churn Rate (%)")
plt.legend(title="Contract")
plt.show()

contract_churn = (
    df.groupby("Contract", observed=True)["Churn_Encoded"]
    .mean()
    .reset_index()
)

contract_churn["Churn_Encoded"] *= 100

contract_churn

plt.figure(figsize=(8, 5))

sns.barplot(
    data=contract_churn,
    x="Contract",
    y="Churn_Encoded"
)

plt.title("Churn Rate by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Churn Rate (%)")
plt.show()

payment_churn = (
    df.groupby("PaymentMethod")["Churn_Encoded"]
    .mean()
    .reset_index()
)

payment_churn["Churn_Encoded"] *= 100

payment_churn

plt.figure(figsize=(10, 5))

sns.barplot(
    data=payment_churn,
    x="PaymentMethod",
    y="Churn_Encoded"
)

plt.title("Churn Rate by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Churn Rate (%)")
plt.xticks(rotation=30)
plt.show()

# Calculate churn rate by Internet Service

internet_churn = (
    df.groupby("InternetService", observed=True)["Churn_Encoded"]
    .mean()
    .reset_index(name="Churn_Rate")
)

# Convert to percentage
internet_churn["Churn_Rate"] *= 100

internet_churn

plt.figure(figsize=(8, 5))

sns.barplot(
    data=internet_churn,
    x="InternetService",
    y="Churn_Rate"
)

plt.title("Churn Rate by Internet Service")
plt.xlabel("Internet Service")
plt.ylabel("Churn Rate (%)")
plt.show()

# Calculate churn rate by Senior Citizen status

senior_churn = (
    df.groupby("SeniorCitizen")["Churn_Encoded"]
    .mean()
    .reset_index(name="Churn_Rate")
)

senior_churn["Churn_Rate"] *= 100

senior_churn

plt.figure(figsize=(7, 5))

sns.barplot(
    data=senior_churn,
    x="SeniorCitizen",
    y="Churn_Rate"
)

plt.title("Churn Rate by Senior Citizen Status")
plt.xlabel("Senior Citizen (0 = No, 1 = Yes)")
plt.ylabel("Churn Rate (%)")
plt.show()

# Calculate churn rate by Partner status

partner_churn = (
    df.groupby("Partner")["Churn_Encoded"]
    .mean()
    .reset_index(name="Churn_Rate")
)

partner_churn["Churn_Rate"] *= 100

partner_churn

plt.figure(figsize=(7, 5))

sns.barplot(
    data=partner_churn,
    x="Partner",
    y="Churn_Rate"
)

plt.title("Churn Rate by Partner Status")
plt.xlabel("Partner")
plt.ylabel("Churn Rate (%)")
plt.show()

# Customer lifetime analysis

df["tenure"].describe()

# Average tenure of churned and retained customers

lifetime_churn = (
    df.groupby("Churn")["tenure"]
    .mean()
    .reset_index()
)

lifetime_churn

plt.figure(figsize=(7, 5))

sns.barplot(
    data=lifetime_churn,
    x="Churn",
    y="tenure"
)

plt.title("Average Customer Lifetime by Churn Status")
plt.xlabel("Churn Status")
plt.ylabel("Average Tenure (Months)")
plt.show()

# Customer cohort analysis using tenure groups

cohort_analysis = (
    df.groupby("Tenure_Group", observed=True)
    .agg(
        Customers=("customerID", "count"),
        Churn_Rate=("Churn_Encoded", "mean")
    )
    .reset_index()
)

cohort_analysis["Churn_Rate"] *= 100

cohort_analysis

plt.figure(figsize=(9, 5))

sns.barplot(
    data=cohort_analysis,
    x="Tenure_Group",
    y="Churn_Rate"
)

plt.title("Churn Rate by Customer Tenure Group")
plt.xlabel("Tenure Group")
plt.ylabel("Churn Rate (%)")
plt.show()

# Overall churn and retention rate

overall_churn = df["Churn_Encoded"].mean() * 100
overall_retention = 100 - overall_churn

print(f"Overall Churn Rate: {overall_churn:.2f}%")
print(f"Overall Retention Rate: {overall_retention:.2f}%")

# Key business insights

highest_churn_contract = contract_churn.loc[
    contract_churn["Churn_Encoded"].idxmax(), "Contract"
]

highest_churn_contract_rate = contract_churn["Churn_Encoded"].max()

print("KEY INSIGHTS")
print("-" * 50)

print(f"1. Overall churn rate is {overall_churn:.2f}%.")
print(f"2. Overall retention rate is {overall_retention:.2f}%.")
print(f"3. The contract type with the highest churn is '{highest_churn_contract}' "
      f"with a churn rate of {highest_churn_contract_rate:.2f}%.")
print("4. Customers with shorter tenure generally show higher churn.")
print("5. Longer-tenure customers are generally more likely to remain with the company.")

# Recommendations to reduce customer churn

print("RECOMMENDATIONS")
print("-" * 50)

print("1. Provide incentives to move customers from short-term to long-term contracts.")
print("2. Focus retention campaigns on new and low-tenure customers.")
print("3. Offer personalized plans and discounts to customers showing churn risk.")
print("4. Improve customer support and service experience.")
print("5. Regularly monitor churn rates across customer segments.")

# Save cleaned dataset for Power BI

df.to_csv("Telco_Customer_Churn_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully.")

from google.colab import files

files.download("Telco_Customer_Churn_Cleaned.csv")

# Final summary of important churn metrics

summary = pd.DataFrame({
    "Metric": [
        "Total Customers",
        "Churned Customers",
        "Retained Customers",
        "Overall Churn Rate (%)",
        "Overall Retention Rate (%)",
        "Average Tenure (Months)"
    ],
    "Value": [
        len(df),
        df["Churn_Encoded"].sum(),
        len(df) - df["Churn_Encoded"].sum(),
        overall_churn,
        overall_retention,
        df["tenure"].mean()
    ]
})

summary

# Create a simple final churn analysis dashboard

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# 1. Churn Distribution
sns.countplot(data=df, x="Churn", ax=axes[0, 0])
axes[0, 0].set_title("Customer Churn Distribution")
axes[0, 0].set_xlabel("Churn")
axes[0, 0].set_ylabel("Number of Customers")

# 2. Churn by Contract
sns.barplot(
    data=contract_churn,
    x="Contract",
    y="Churn_Encoded",
    ax=axes[0, 1]
)
axes[0, 1].set_title("Churn Rate by Contract")
axes[0, 1].set_xlabel("Contract")
axes[0, 1].set_ylabel("Churn Rate (%)")

# 3. Churn by Tenure Group
sns.barplot(
    data=cohort_analysis,
    x="Tenure_Group",
    y="Churn_Rate",
    ax=axes[1, 0]
)
axes[1, 0].set_title("Churn Rate by Tenure Group")
axes[1, 0].set_xlabel("Tenure Group")
axes[1, 0].set_ylabel("Churn Rate (%)")

# 4. Churn by Internet Service
sns.barplot(
    data=internet_churn,
    x="InternetService",
    y="Churn_Rate",
    ax=axes[1, 1]
)
axes[1, 1].set_title("Churn Rate by Internet Service")
axes[1, 1].set_xlabel("Internet Service")
axes[1, 1].set_ylabel("Churn Rate (%)")

plt.tight_layout()
plt.show()

# Final business conclusion

print("=" * 60)
print("CUSTOMER RETENTION & CHURN ANALYSIS - FINAL CONCLUSION")
print("=" * 60)

print(f"\nOverall Churn Rate: {overall_churn:.2f}%")
print(f"Overall Retention Rate: {overall_retention:.2f}%")
print(f"Average Customer Tenure: {df['tenure'].mean():.2f} months")

print("\nKEY FINDINGS:")
print("• Churn is an important customer retention challenge.")
print("• Customers with shorter tenure are more likely to churn.")
print("• Contract type has a noticeable impact on customer churn.")
print("• Longer-tenure customers generally show better retention.")
print("• Internet service type also shows differences in churn behavior.")

print("\nRECOMMENDATIONS:")
print("• Target new customers with early-stage retention campaigns.")
print("• Encourage customers to choose longer-term contracts.")
print("• Provide personalized offers to high-risk customers.")
print("• Improve customer service and overall customer experience.")
print("• Monitor churn regularly to identify changing customer behavior.")

print("\nCONCLUSION:")
print("The analysis shows that customer tenure and contract type are")
print("important factors related to churn. The business should focus")
print("on retaining new customers and encouraging long-term contracts.")

# Save important analysis tables

with pd.ExcelWriter("Churn_Analysis_Report.xlsx") as writer:
    summary.to_excel(writer, sheet_name="Summary", index=False)
    contract_churn.to_excel(writer, sheet_name="Contract_Churn", index=False)
    cohort_analysis.to_excel(writer, sheet_name="Tenure_Cohort", index=False)
    internet_churn.to_excel(writer, sheet_name="Internet_Churn", index=False)
    lifetime_churn.to_excel(writer, sheet_name="Customer_Lifetime", index=False)

print("Churn analysis report created successfully.")

from google.colab import files

files.download("Churn_Analysis_Report.xlsx")

# Create and save final dashboard image

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# 1. Churn Distribution
sns.countplot(data=df, x="Churn", ax=axes[0, 0])
axes[0, 0].set_title("Customer Churn Distribution")
axes[0, 0].set_xlabel("Churn")
axes[0, 0].set_ylabel("Number of Customers")

# 2. Churn by Contract
sns.barplot(
    data=contract_churn,
    x="Contract",
    y="Churn_Encoded",
    ax=axes[0, 1]
)
axes[0, 1].set_title("Churn Rate by Contract")
axes[0, 1].set_xlabel("Contract")
axes[0, 1].set_ylabel("Churn Rate (%)")

# 3. Churn by Tenure Group
sns.barplot(
    data=cohort_analysis,
    x="Tenure_Group",
    y="Churn_Rate",
    ax=axes[1, 0]
)
axes[1, 0].set_title("Churn Rate by Tenure Group")
axes[1, 0].set_xlabel("Tenure Group")
axes[1, 0].set_ylabel("Churn Rate (%)")

# 4. Churn by Internet Service
sns.barplot(
    data=internet_churn,
    x="InternetService",
    y="Churn_Rate",
    ax=axes[1, 1]
)
axes[1, 1].set_title("Churn Rate by Internet Service")
axes[1, 1].set_xlabel("Internet Service")
axes[1, 1].set_ylabel("Churn Rate (%)")

plt.suptitle(
    "Customer Retention & Churn Analysis",
    fontsize=18,
    fontweight="bold"
)

plt.tight_layout()

# Save dashboard as image
plt.savefig(
    "churn_analysis_dashboard.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from google.colab import files

files.download("churn_analysis_dashboard.png")

